### ISSUE TITLE
Make libraries available in python3 optional

### ISSUE THREAD

**Issue by mcepl** [testing-cabal/traceback2#13]
While trying to trim requirements on our packages as lean as possible I have developed [this patch](https://github.com/testing-cabal/traceback2/files/2372591/optional_alternative_impls.patch.txt). I think really dependency on such libraries as ``unittest2`` (unnecessary for any upstream supported version of Python) should be strictly optional, so that this library my finally get its deserved rest.

**Comment by jelmer** [comment]
Removed in #17
